name: Build release

on: 
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  building:
    name: Building
    continue-on-error: ${{ matrix.experimental || false }}
    strategy:
      matrix:
        # All generated code should be running on stable now
        rust: [ stable ]
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: thumbv6m-none-eabi
      - run: sudo apt update
      - run: sudo apt -y install libudev-dev
      - run: cargo install flip-link
      - run: cargo install elf2uf2-rs
      - run: cargo build --release
      - run: ~/.cargo/bin/elf2uf2-rs target/thumbv6m-none-eabi/release/nine_pin_to_supergun 9pin2supergun-pcb-${{ github.ref }}.uf2
      - run: cargo build --release --features=pi_pico
      - run: ~/.cargo/bin/elf2uf2-rs target/thumbv6m-none-eabi/release/nine_pin_to_supergun 9pin2supergun-pico-${{ github.ref }}.uf2
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.uf2"
          make_latest: true
