name: Render KiCad files (PCB)
on:
  push:
    paths:
      - "pcb/*.kicad_*"
jobs:
  generate_files:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Render project
        uses: sparkengineering/kicad-action@v4
        id: production
        with:
          kicad_sch: pcb/9pin2supergun.kicad_sch
          sch_pdf: true
          sch_bom: true 
          kicad_pcb: pcb/9pin2supergun.kicad_pcb
          pcb_gerbers: true
          pcb_image: true
      - name: Upload production files
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.production.conclusion == 'success' }}
        with:
          name: pcb-rendered
          path: |
            ${{ github.workspace }}/pcb/sch.pdf
            ${{ github.workspace }}/pcb/gbr.zip
            ${{ github.workspace }}/pcb/bom.csv
            ${{ github.workspace }}/pcb/images/top.png
            ${{ github.workspace }}/pcb/images/bottom.png
      - name: Download production files
        uses: actions/download-artifact@v4
        with:
          name: pcb-rendered
          path: ${{github.workspace}}/pcb/rendered
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Render schematics and gerbers
          file_pattern: "pcb/rendered/*"
